name: On Merge in Main

on:
  pull_request:
    branches:
      - main
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
jobs:
  
  sonarcloud-security-analysis:
    runs-on: alpine-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          fetch-depth: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
